### ISSUE TITLE
调用下载时报错

### ISSUE THREAD

**Issue by zqj** [lanrion/qy_wechat_api#12]
media_id = "xICvlUNt6cDIJLris5Dkxb9NUJQ4P7uS7R4GuGSEjeqhHCDjYNgkSs-EFjpxnS_n"

client.media.get_media_by_id(media_id)

错误提示为：

JSON::ParserError (lexical error: invalid char in json text.
                                       ????                     (right here) ------^
):

**Comment by lanrion** [comment]
返回一条下载链接。
