### ISSUE TITLE
微信企业号登录接口反馈

### ISSUE THREAD

**Issue by zqj** [lanrion/qy_wechat_api#13]
group_client = QyWechatApi::Client.new(@@corp_id, @@provider_secret)
   
1.  group_client.auth_login.get_provider_token(@@provider_secret)
     
2.  group_client.auth_login.get_login_info_by_secret(params[:auth_code], @@provider_secret)

调用1、2调用时，报错如下

RestClient::ResourceNotFound (404 Resource Not Found):

**Comment by zqj** [comment]
login_ticket:::::?auth_code= cdf75a966c98b5d568b998f73963365c&state=wx_qyh_login_xiaoshouke_89221&expires_in=600 provider_secret=YZ6RuOpinmrGb3kpSfkjO_BzL1ydX-lWUz8A5WF64WghwfAkOM9gUJpe-93FtMFN
QyAuthCode access_token Exception: RestClient::ResourceNotFound : 404 Resource Not Found
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/abstract_response.rb:48:in `return!'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:495:in `process_result'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:421:in `block in transmit'
/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:853:in `start'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient.rb:69:in `post'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat_api-04749fb0d4af/lib/qy_wechat_api.rb:38:in `http_post_without_token'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat_api-04749fb0d4af/lib/qy_wechat_api/api/auth_login.rb:25:in `block in get_provider_token'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache.rb:296:in `block in fetch'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache.rb:587:in `block in save_block_result_to_cache'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache.rb:548:in `instrument'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache.rb:586:in `save_block_result_to_cache'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache.rb:296:in `fetch'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat_api-04749fb0d4af/lib/qy_wechat_api/api/auth_login.rb:22:in `get_provider_token'
/home/deploy/xiaoshouke/releases/20150720014542/app/controllers/qy_services_controller.rb:101:in `login_ticket'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:189:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'

**Comment by lanrion** [comment]
fixed, test again.

**Comment by zqj** [comment]
login_ticket: auth_code= bd455a030f1488f697417fec2d631c0e&state=wx_qyh_login_xiaoshouke_89221&expires_in=600 provider_secret=YZ6RuOpinmrGb3kpSfkjO_BzL1ydX-lWUz8A5WF64WghwfAkOM9gUJpe-93FtMFN
login_ticket: wx_qyh_login_xiaoshouke_89221
url: /service/get_login_info?provider_access_token=S0uDLZoNVZGgo8QVZ5qJJ6HGaj9a-JSdpQs9IvP87SJeDfaBHeZBMH4VP3brX1CE-- payload: {:auth_code=>"bd455a030f1488f697417fec2d631c0e"}-- params: {}
url: /service/get_login_info?provider_access_token=S0uDLZoNVZGgo8QVZ5qJJ6HGaj9a-JSdpQs9IvP87SJeDfaBHeZBMH4VP3brX1CE-- payload: {:auth_code=>"bd455a030f1488f697417fec2d631c0e"}-- params: {}
login_info : 不合法的oauth_code
Redirected to http://crm.xiaoshouke.cn/admin?redirect_key=login_ticket

**Comment by lanrion** [comment]
fixed
