### ISSUE TITLE
获取应用概况列表,报错，和上次那个问题差不多！

### ISSUE THREAD

**Issue by zqj** [lanrion/qy_wechat_api#14]
# 获取应用概况列表
 group_client.agent.list 

QyAuthAgent agent syn : RestClient::ResourceNotFound : 404 Resource Not Found
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/abstract_response.rb:48:in `return!'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:495:in `process_result'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:421:in `block in transmit'
/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:853:in `start'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient.rb:65:in `get'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat_api-f5ad0b713fab/lib/qy_wechat_api.rb:31:in `http_get_without_token'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat_api-f5ad0b713fab/lib/qy_wechat_api/api/base.rb:16:in `http_get'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat_api-f5ad0b713fab/lib/qy_wechat_api/api/agent.rb:16:in `list'
/home/deploy/xiaoshouke/releases/20150724132006/app/models/qy_auth_agent.rb:318:in `syn'
/home/deploy/xiaoshouke/releases/20150724132006/app/controllers/qy_auth_agents_controller.rb:8:in `index'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:189:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `block in halting'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `block in instrument'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `instrument'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:136:in `process'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionview-4.1.8/lib/action_view/rendering.rb:30:in `process'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal.rb:196:in `dispatch'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal.rb:232:in `block in action'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:50:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/simple_captcha2-0.3.4/lib/simple_captcha/middleware.rb:26:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rack-1.5.3/lib/rack/etag.rb:23:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rack-1.5.3/lib/rack/conditionalget.rb:25:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rack-1.5.3/lib/rack/head.rb:11:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/flash.rb:254:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rack-1.5.3/lib/rack/session/abstract/id.rb:225:in `context'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rack-1.5.3/lib/rack/session/abstract/id.rb:220:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/query_cache.rb:36:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:38:in `call_app'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `block in call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rack-1.5.3/lib/rack/methodoverride.rb:21:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rack-1.5.3/lib/rack/runtime.rb:17:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rack-1.5.3/lib/rack/sendfile.rb:112:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/application.rb:144:in `call'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `public_send'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/rvm/gems/ruby-2.1.4@rails418/gems/passenger-4.0.53/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/local/rvm/gems/ruby-2.1.4@rails418/gems/passenger-4.0.53/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/local/rvm/gems/ruby-2.1.4@rails418/gems/passenger-4.0.53/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/local/rvm/gems/ruby-2.1.4@rails418/gems/passenger-4.0.53/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

**Comment by zqj** [comment]
qy_auth_code.expires_in 2015-05-28 12:26
url: /service/get_corp_token-- payload: {:auth_corpid=>"wxfac088bb438a96d7", :permanent_code=>"7oUm_pow832p8peTOH6h92HgzrUkOtTkgK_rQwcWE9t1HdlUtfB47jelnJt1v7ur", :suite_id=>"tjbfe3c9af45f0d997"}-- params: {:suite_access_token=>"LTy_94ZuplYiJ4NAoXQHQWy_4W97wnCw8QWGIIJfIB7AEXZt8TX45gBGKSfM7Z5x"}
QySuite.update_corp_token : 40084 {}
access_token 2 fyYzPgNgnYLAQ2_leMWfAsEaT_xuhv_j0lVtSlO4WnMko3e6z-IP9Mz33ge62zPZ
url: /gettoken--- params: {:corpid=>"wxfac088bb438a96d7", :corpsecret=>"m7KAC_Mp0eN9oSuuJcRfREvy2fHEjUlQ0fe2fCbcjm2pqu42k-I3UO5ZzFhrbHaP"}
 is_valid? : true
url: /gettoken--- params: {:corpid=>"wxfac088bb438a96d7", :corpsecret=>"m7KAC_Mp0eN9oSuuJcRfREvy2fHEjUlQ0fe2fCbcjm2pqu42k-I3UO5ZzFhrbHaP"}
agent syn ...
url: /gettoken--- params: {:corpid=>"wxfac088bb438a96d7", :corpsecret=>"m7KAC_Mp0eN9oSuuJcRfREvy2fHEjUlQ0fe2fCbcjm2pqu42k-I3UO5ZzFhrbHaP"}
url: /list--- params: {:access_token=>"Yex2U9zl9N8532U-wXqDLjcBQvly0FH5Dvkxe9yH4rMs9cBqGiOdlPkD_cZMGY26mB2VEle2N0r1CF8izb5XKw"}
QyAuthAgent agent syn : RestClient::ResourceNotFound : 404 Resource Not Found
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/abstract_response.rb:48:in `return!'
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.3/lib/restclient/request.rb:495:in `process_result'

**Comment by lanrion** [comment]
fixed.
