### ISSUE TITLE
新接口－获取登录企业号官网的url

### ISSUE THREAD

**Issue by zqj** [lanrion/qy_wechat_api#20]
http://qydev.weixin.qq.com/wiki/index.php?title=%E8%8E%B7%E5%8F%96%E7%99%BB%E5%BD%95%E4%BC%81%E4%B8%9A%E5%8F%B7%E5%AE%98%E7%BD%91%E7%9A%84url

**Comment by lanrion** [comment]
```ruby
# 获取登录企业号官网的url
suite_api.get_login_url(ticket, provider_token, target, agentid=nil)
```
