### ISSUE TITLE
获取登录企业号官网的url 一直报错

### ISSUE THREAD

**Issue by zqj** [lanrion/qy_wechat_api#21]
41001	缺少access_token参数

http://qydev.weixin.qq.com/wiki/index.php?title=%E8%8E%B7%E5%8F%96%E7%99%BB%E5%BD%95%E4%BC%81%E4%B8%9A%E5%8F%B7%E5%AE%98%E7%BD%91%E7%9A%84url

**Comment by zqj** [comment]
这个接口，应该是在这个 group_client.auth_login 下面吧！

**Comment by lanrion** [comment]
重构后：
```ruby
group_client.auth_login.get_login_url(ticket, provider_token, target, agentid=nil)
```
